### ISSUE TITLE
Running rport failed on vmware esxi

### ISSUE THREAD

**Issue by hermanntoast** [cloudradar-monitoring/rport#505]
I try to run rport on a vmware esxi an got the following error message:

```
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw({0x8bea68, 0xc000097840})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.netpoll(0xc00002c000)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/netpoll_epoll.go:131 +0x316
runtime.findrunnable()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:2947 +0x593
runtime.schedule()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:3367 +0x239
runtime.park_m(0xc000001380)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:3516 +0x14d
runtime.mcall()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:307 +0x43

goroutine 1 [chan receive]:
[github.com/kardianos/service.(*sysv](http://github.com/kardianos/service.(*sysv)).Run.func1()
	/home/runner/go/pkg/mod/github.com/kardianos/service@v1.1.0/service_sysv_linux.go:147 +0x89
[github.com/kardianos/service.(*sysv](http://github.com/kardianos/service.(*sysv)).Run(0xc00027c630)
	/home/runner/go/pkg/mod/github.com/kardianos/service@v1.1.0/service_sysv_linux.go:148 +0x92
main.runAsService(0xc000124660, {0x39547bcbea7, 0x2})
	/home/runner/work/rport/rport/cmd/rport/service.go:34 +0x43
main.runMain(0xc00015f340, {0xc000155020, 0x0, 0x2})
	/home/runner/work/rport/rport/cmd/rport/main.go:434 +0x439
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).execute(0xc00015f340, {0xc000124160, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).ExecuteC(0xc00015f340)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
[github.com/spf13/cobra.(*Command](http://github.com/spf13/cobra.(*Command)).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/rport/rport/cmd/rport/main.go:343 +0x25

goroutine 18 [chan receive]:
[github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).Wait(...)
	/home/runner/work/rport/rport/client/client.go:449
[github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).Run(0xc00018a880)
	/home/runner/work/rport/rport/client/client.go:96 +0xb0
main.(*serviceWrapper).Start.func1()
	/home/runner/work/rport/rport/cmd/rport/service.go:58 +0x25
created by main.(*serviceWrapper).Start
	/home/runner/work/rport/rport/cmd/rport/service.go:57 +0x65

goroutine 5 [sleep]:
time.Sleep(0x6fc23ac00)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/time.go:193 +0x12e
[github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).keepAliveLoop(0xc00018a880)
	/home/runner/work/rport/rport/client/client.go:126 +0x3c
created by [github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).Start
	/home/runner/work/rport/rport/client/client.go:114 +0x7f

goroutine 6 [select]:
[github.com/cloudradar-monitoring/rport/share.SleepSignal(0x5f5e100)](http://github.com/cloudradar-monitoring/rport/share.SleepSignal(0x5f5e100))
	/home/runner/work/rport/rport/share/signal.go:19 +0xb1
[github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).connectionLoop(0xc00018a880, {0x960918, 0xc0000b6000})
	/home/runner/work/rport/rport/client/client.go:149 +0x23e
created by [github.com/cloudradar-monitoring/rport/client.(*Client](http://github.com/cloudradar-monitoring/rport/client.(*Client)).Start
	/home/runner/work/rport/rport/client/client.go:117 +0xe5

goroutine 7 [select]:
[github.com/cloudradar-monitoring/rport/client/updates.(*Updates](http://github.com/cloudradar-monitoring/rport/client/updates.(*Updates)).refreshLoop(0xc000262c00, {0x960918, 0xc0000b6000})
	/home/runner/work/rport/rport/client/updates/updates.go:75 +0xda
created by [github.com/cloudradar-monitoring/rport/client/updates.(*Updates](http://github.com/cloudradar-monitoring/rport/client/updates.(*Updates)).Start
	/home/runner/work/rport/rport/client/updates/updates.go:48 +0x9d

goroutine 20 [syscall]:
os/signal.signal_recv()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/opt/hostedtoolcache/go/1.17.7/x64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.17.7/x64/src/os/signal/signal.go:151 +0x2c
```

My ESXi runs version 7.0.2.

**Comment by hermanntoast** [comment]
Hey @thorstenkramm . Thanks for the fast reply. I thought I'd give it a try, but of course I understand that it's not that easy.

Thank you anyway, best regards
