### ISSUE TITLE
letsencrypt certbot can't renew automatically because rportd is using port 80 

### ISSUE THREAD

**Issue by guntisratkevics** [cloudradar-monitoring/rport#613]
I instaled rport on premises by recumendations from [https://kb.rport.io/install-the-rport-server/install-on-premises#intranet-installation-with-internet-operation](url)
But it seems that certbot with its default timer can't renew letsencrypt certificate automatically because rportd is using port 80

```
2022-07-03 06:00:30,884:DEBUG:acme.standalone:Failed to bind to :80 using IPv6
2022-07-03 06:00:30,884:DEBUG:acme.standalone:Failed to bind to :80 using IPv4
2022-07-03 06:00:30,884:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 71, in run
    servers = acme_standalone.HTTP01DualNetworkedServers(
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 190, in __init__
    BaseDualNetworkedServers.__init__(self, HTTP01Server, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 105, in __init__
    raise socket.error("Could not bind to IPv4 or IPv6.")
OSError: Could not bind to IPv4 or IPv6.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 156, in perform
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 156, in <listcomp>
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 163, in _try_perform_single
    _handle_perform_error(error)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 210, in _handle_perform_error
    raise error
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 161, in _try_perform_single
    return self._perform_single(achall)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 166, in _perform_single
    servers, response = self._perform_http_01(achall)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 173, in _perform_http_01
    servers = self.servers.run(port, challenges.HTTP01, listenaddr=addr)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 74, in run
    raise errors.StandaloneBindError(error, port)
certbot.errors.StandaloneBindError: Problem binding to port 80: Could not bind to IPv4 or IPv6.

2022-07-03 06:00:30,884:DEBUG:certbot._internal.error_handler:Calling registered functions
2022-07-03 06:00:30,885:INFO:certbot._internal.auth_handler:Cleaning up challenges
2022-07-03 06:00:30,885:ERROR:certbot._internal.renewal:Failed to renew certificate rport.xx.xx with error: Problem binding to port 80: Could not bind to IPv4 or IPv6.
2022-07-03 06:00:30,886:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 71, in run
    servers = acme_standalone.HTTP01DualNetworkedServers(
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 190, in __init__
    BaseDualNetworkedServers.__init__(self, HTTP01Server, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 105, in __init__
    raise socket.error("Could not bind to IPv4 or IPv6.")
OSError: Could not bind to IPv4 or IPv6.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/renewal.py", line 485, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1234, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 123, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3/dist-packages/certbot/_internal/renewal.py", line 345, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 156, in perform
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 156, in <listcomp>
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 163, in _try_perform_single
    _handle_perform_error(error)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 210, in _handle_perform_error
    raise error
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 161, in _try_perform_single
    return self._perform_single(achall)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 166, in _perform_single
    servers, response = self._perform_http_01(achall)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 173, in _perform_http_01
    servers = self.servers.run(port, challenges.HTTP01, listenaddr=addr)
  File "/usr/lib/python3/dist-packages/certbot/_internal/plugins/standalone.py", line 74, in run
    raise errors.StandaloneBindError(error, port)
certbot.errors.StandaloneBindError: Problem binding to port 80: Could not bind to IPv4 or IPv6.

2022-07-03 06:00:30,886:DEBUG:certbot.display.util:Notifying user:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-07-03 06:00:30,886:ERROR:certbot._internal.renewal:All renewals failed. The following certificates could not be renewed:
2022-07-03 06:00:30,886:ERROR:certbot._internal.renewal:  /etc/letsencrypt/live/rport.xx.xx/fullchain.pem (failure)
2022-07-03 06:00:30,886:DEBUG:certbot.display.util:Notifying user: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-07-03 06:00:30,886:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.12.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1413, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1317, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3/dist-packages/certbot/_internal/renewal.py", line 510, in handle_renewal_request
    raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)
2022-07-03 06:00:30,886:ERROR:certbot._internal.log:1 renew failure(s), 0 parse failure(s)

```

**Comment by thorstenkramm** [comment]
@guntisratkevics You should not alter `/lib/systemd/system/certbot.timer`.
`/etc/letsencrypt/renewal-hooks/pre` is the proper location to place a script that stops rport. And in `/etc/letsencrypt/renewal-hooks/post` you put a script to start rport again after the renewal.

**Comment by guntisratkevics** [comment]
Ok, seams to work. 
I did:

echo 'systemctl stop rportd' | sudo tee /etc/letsencrypt/renewal-hooks/pre/stop_rportd.sh && chmod +x /etc/letsencrypt/renewal-hooks/pre/stop_rportd.sh

echo 'systemctl start rportd' | sudo tee /etc/letsencrypt/renewal-hooks/post/start_rportd.sh && chmod +x /etc/letsencrypt/renewal-hooks/pre/start_rportd.sh

**Comment by thorstenkramm** [comment]
@guntisratkevics Have you verified certbot calls the scripts with `sh`? Or does certbot just execute them? For the latter, the scripts would need shebang.

**Comment by guntisratkevics** [comment]
I did not try without `sh`. It did not work without `sudo chmod +x`

**Comment by thorstenkramm** [comment]
@guntisratkevics Just to be safe, I would add a shebang.
```
#!/bin/sh
systemctl start rportd
```

**Comment by rseuster** [comment]
I had the same problem - would be nice, if the documentation would be updated with this info.
