### ISSUE TITLE
External component has thrown an exception

### ISSUE THREAD

**Issue by fromage9747** [cloudradar-monitoring/rport#966]
OS: Windows 10
1 out of 3 machines that I have installed the Windows Client on and got this issue.

The other two devices installed and connected up without issue.

PowerShell is being run as administrator. 

`Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeString()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeMemberName()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.InvokeRestMethodCommand.TryConvertToJson(String json, Object& obj, Exception& exRef)
   at Microsoft.PowerShell.Commands.InvokeRestMethodCommand.ProcessResponse(WebResponse response)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by thorstenkramm** [comment]
@fromage9747 We are all happy to help you. But without more context, it's not possible. Just copying and pasting a message from the terminal is not enough.

Which command has produced the pasted output?
Did you get the output on the terminal, the browser, or did you grab it from a log file? If the latter is the case, which file was it?
During which operation the above messages were produced? New client pairing? Command or script execution? Tunnel creation?

**Comment by fromage9747** [comment]
@thorstenkramm To be clear I said "1 out of 3 machines that I have installed the Windows Client on and got this issue.

**_The other two devices installed and connected up without issue._**"

Windows is in English on all 3 machines. 

Machine 1 Windows Server 2016, successful install PSVersion 5.1.14393.5582:

![image](https://user-images.githubusercontent.com/23147783/226323730-18ab9ec6-f408-40a1-a035-9cfdfa465cfa.png)

Machine 2 Windows 10 Successful install PSVersion  5.1.19041.2673:

![image](https://user-images.githubusercontent.com/23147783/226324076-c741253d-8cb1-48d4-ad0d-960356003883.png)

Machine 3 Windows 10 failed install PSVersion  5.1.19041.2673:

![image](https://user-images.githubusercontent.com/23147783/226324214-5bf411cb-6bb8-43cd-b2d4-2d2ed7f29e8d.png)

I don't think the issue has to do with the PowerShell version.  Especially as my Server 2016 machine is running a lower version, and it successfully installed. 

To give you the benefit of the doubt, I will install PowerShell 7 and let you know.  👍

**Comment by thorstenkramm** [comment]
@fromage9747 It's very likely not the PowerShell version. But Googling for the `SEHException` gave me hints about a messed PowerShell can cause the issue. By installing PowerShell 7 you get an independent virgin PowerShell. 
This exercise is just for narrowing the root cause. Is it the script itself, or is it the particular PowerShell?

**Comment by fromage9747** [comment]
@thorstenkramm Anything else I should look into?

**Comment by thorstenkramm** [comment]
@thorstenkramm The file reception step has been executed successfully. Next step is getting the country and city of the system.
What happens if you execute this manually in a PowerShell
```powershell
# Get the location of the server
$geoUrl = "http://ip-api.com/json/?fields=status,country,city"
try
{
    $geoData = Invoke-RestMethod -Uri $geoUrl -TimeoutSec 5
    if ("success" -eq $geoData.status)
    {
        # Add geo data as tags
        $tags += $geoData.country
        $tags += $geoData.city
    }
}
catch
{
    Write-Output ": Fetching geodata failed. Skipping"
}
$geodata
```

Take the pairing script and execute all steps manuall after 
```
# Enable/Disable file reception
$configContent = Enable-FileReception -ConfigContent $configContent -Switch $r
```
This way, you can narrow what exactly provokes the issue.

**Comment by fromage9747** [comment]
@thorstenkramm Thanks for this.  You pointed me in the right direction. 

It has now installed successfully, just not able to connect.  This is the second device I have installed on today that is not able to connect.

Is there a limit to the number of devices?

**Comment by fromage9747** [comment]
@thorstenkramm Got it working using this: https://github.com/realvnc-labs/rport/issues/887 I had to change the system_id in the conf file.

As soon as I changed it to the one in the example conf file and started the service, it connected up.
